Repository dnd-side-project/dnd-11th-7-backend, pull requests merged in 2024-09, with the labels that each got.

#91 Refactor/#89 CSRF 수정 (MockMVC)
  src/main/resources/static/index.html
  src/test/java/com/dnd/jjakkak/config/AbstractRestDocsTest.java
Labels: refactor

#87 Feature/#85 모임 일정
  src/docs/asciidoc/api/schedule.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryCustom.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryImpl.java
  src/main/java/com/dnd/jjakkak/domain/schedule/controller/ScheduleController.java
  src/main/java/com/dnd/jjakkak/domain/schedule/dto/request/ScheduleAssignRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/schedule/dto/request/ScheduleUpdateRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/schedule/dto/response/ScheduleResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/schedule/repository/ScheduleRepositoryCustom.java
  src/main/java/com/dnd/jjakkak/domain/schedule/repository/ScheduleRepositoryImpl.java
  src/main/java/com/dnd/jjakkak/domain/schedule/service/ScheduleService.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityEndpointPaths.java
  src/main/resources/static/index.html
  src/test/java/com/dnd/jjakkak/domain/meeting/MeetingDummy.java
  src/test/java/com/dnd/jjakkak/domain/schedule/ScheduleDummy.java
  src/test/java/com/dnd/jjakkak/domain/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/schedule/repository/ScheduleRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/schedule/service/ScheduleServiceTest.java
Labels: feature

#94 [Refactor] 서버 에러 처리 수정
  src/main/java/com/dnd/jjakkak/global/exception/ExceptionController.java
Labels: refactor

#100 [Refactor] 로그아웃 핸들러 수정
  src/main/java/com/dnd/jjakkak/domain/jwt/exception/TokenExpiredException.java
  src/main/java/com/dnd/jjakkak/domain/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2LogoutHandler.java
  src/main/java/com/dnd/jjakkak/domain/jwt/provider/JwtProvider.java
  src/main/java/com/dnd/jjakkak/domain/member/repository/MemberRepository.java
  src/main/java/com/dnd/jjakkak/domain/member/service/AuthService.java
  src/main/java/com/dnd/jjakkak/domain/member/service/BlacklistService.java
  src/test/java/com/dnd/jjakkak/domain/member/service/BlacklistServiceTest.java
Labels: refactor

#99 [Refactor] 모임 일정의 우선 순위 (rank) 고정
  src/main/java/com/dnd/jjakkak/domain/dateofschedule/service/DateOfScheduleService.java
Labels: refactor

#101 Feature/#97 oauth failure handler
  src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2FailureHandler.java
  src/main/resources/static/index.html
Labels: refactor

#104 [Refactor] 모임 관련 리팩토링 및 오류 수정
  src/main/java/com/dnd/jjakkak/domain/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/dnd/jjakkak/domain/meeting/controller/MeetingController.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingTime.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingTimeResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryCustom.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryImpl.java
  src/main/java/com/dnd/jjakkak/domain/meeting/service/MeetingService.java
  src/main/java/com/dnd/jjakkak/domain/schedule/controller/ScheduleController.java
  src/main/java/com/dnd/jjakkak/domain/schedule/service/ScheduleService.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityEndpointPaths.java
  src/main/resources/static/index.html
  src/test/java/com/dnd/jjakkak/domain/meeting/MeetingDummy.java
  src/test/java/com/dnd/jjakkak/domain/meeting/controller/MeetingControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/meeting/service/MeetingServiceTest.java
  src/test/java/com/dnd/jjakkak/domain/schedule/service/ScheduleServiceTest.java
Labels: feature, refactor

#106 [Refactor] 로그인 후 리다이렉트 URL 수정
  src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2FailureHandler.java
  src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2SuccessHandler.java
  src/main/java/com/dnd/jjakkak/global/config/security/CustomAuthorizationRequestResolver.java
  src/main/java/com/dnd/jjakkak/global/config/security/FailedAuthenticationEntryPoint.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityConfig.java
Labels: feature

#111 [Fix] 일정 수정 관련 버그 수정
  src/main/java/com/dnd/jjakkak/domain/dateofschedule/repository/DateOfScheduleRepository.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityEndpointPaths.java
Labels: bug

#113 [Feature] 회원 일정 수정 API
  src/main/java/com/dnd/jjakkak/domain/schedule/controller/ScheduleController.java
  src/main/java/com/dnd/jjakkak/domain/schedule/dto/request/ScheduleUpdateRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/schedule/service/ScheduleService.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityEndpointPaths.java
  src/main/resources/static/index.html
  src/test/java/com/dnd/jjakkak/domain/schedule/ScheduleDummy.java
  src/test/java/com/dnd/jjakkak/domain/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/schedule/service/ScheduleServiceTest.java
Labels: feature

#115 [Refactor] 일정 조회 수정 (회원/비회원)
  src/main/java/com/dnd/jjakkak/domain/dateofschedule/dto/response/DateOfScheduleResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/schedule/dto/response/ScheduleResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/schedule/repository/ScheduleRepositoryCustom.java
  src/main/java/com/dnd/jjakkak/domain/schedule/repository/ScheduleRepositoryImpl.java
  src/main/java/com/dnd/jjakkak/domain/schedule/service/ScheduleService.java
  src/main/resources/static/index.html
  src/test/java/com/dnd/jjakkak/domain/schedule/ScheduleDummy.java
  src/test/java/com/dnd/jjakkak/domain/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/schedule/service/ScheduleServiceTest.java
Labels: refactor

#119 Refactor/#118 login redis
  build.gradle
  src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2FailureHandler.java
  src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2LogoutHandler.java
  src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2SuccessHandler.java
  src/main/java/com/dnd/jjakkak/domain/jwt/provider/JwtProvider.java
  src/main/java/com/dnd/jjakkak/domain/member/controller/AuthController.java
  src/main/java/com/dnd/jjakkak/domain/member/dto/response/ReissueResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/member/entity/BlacklistedToken.java
  src/main/java/com/dnd/jjakkak/domain/member/repository/BlacklistedTokenRepository.java
  src/main/java/com/dnd/jjakkak/domain/member/service/AuthService.java
  src/main/java/com/dnd/jjakkak/domain/member/service/BlacklistService.java
  src/main/java/com/dnd/jjakkak/domain/refreshtoken/service/RefreshTokenService.java
  src/main/java/com/dnd/jjakkak/global/config/proprties/TokenProperties.java
  src/main/java/com/dnd/jjakkak/global/config/redis/RedisConfig.java
  src/main/java/com/dnd/jjakkak/global/util/CookieUtils.java
  src/main/resources/static/index.html
  src/test/java/com/dnd/jjakkak/domain/member/controller/AuthControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/member/repository/BlacklistedTokenRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/member/service/BlacklistServiceTest.java
Labels: refactor
