Repository dnd-side-project/dnd-11th-7-backend, pull requests merged in 2024-08, with the labels that each got.

#42 Refactor/#40 oauth2 handler
  src/main/java/com/dnd/jjakkak/domain/member/controller/AuthController.java
  src/main/java/com/dnd/jjakkak/domain/member/jwt/exception/AccessTokenExpiredException.java
  src/main/java/com/dnd/jjakkak/domain/member/jwt/exception/MalformedTokenException.java
  src/main/java/com/dnd/jjakkak/domain/member/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/dnd/jjakkak/domain/member/jwt/handler/OAuth2FailureHandler.java
  src/main/java/com/dnd/jjakkak/domain/member/jwt/handler/OAuth2LogoutHandler.java
  src/main/java/com/dnd/jjakkak/domain/member/jwt/handler/OAuth2SuccessHandler.java
  src/main/java/com/dnd/jjakkak/domain/member/jwt/provider/JwtProvider.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityConfig.java
Labels: 🎨 feature

#41 Feature/#18 모임 리팩토링
  src/main/java/com/dnd/jjakkak/domain/meeting/controller/MeetingController.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/request/MeetingCreateRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/request/MeetingUpdateRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingCreateResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/entity/Meeting.java
  src/main/java/com/dnd/jjakkak/domain/meeting/exception/MeetingUnauthorizedException.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/dnd/jjakkak/domain/meeting/service/MeetingService.java
  src/main/java/com/dnd/jjakkak/domain/meetingmember/entity/MeetingMember.java
  src/main/resources/static/index.html
  src/test/java/com/dnd/jjakkak/domain/meeting/MeetingDummy.java
  src/test/java/com/dnd/jjakkak/domain/meeting/controller/MeetingControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/meeting/service/MeetingServiceTest.java
  src/test/java/com/dnd/jjakkak/domain/meetingcategory/repository/MeetingCategoryRepositoryTest.java
Labels: 🎨 feature

#46 Refactor/#43 모임
  build.gradle
  src/docs/asciidoc/api/meeting.adoc
  src/main/java/com/dnd/jjakkak/domain/meeting/controller/MeetingController.java
  src/main/java/com/dnd/jjakkak/domain/meeting/service/MeetingService.java
  src/main/java/com/dnd/jjakkak/domain/member/jwt/filter/JwtAuthenticationFilter.java
  src/test/java/com/dnd/jjakkak/config/AbstractRestDocsTest.java
  src/test/java/com/dnd/jjakkak/config/JjakkakMockSecurityContext.java
  src/test/java/com/dnd/jjakkak/config/JjakkakMockUser.java
  src/test/java/com/dnd/jjakkak/config/RestDocsConfiguration.java
  src/test/java/com/dnd/jjakkak/domain/meeting/MeetingDummy.java
  src/test/java/com/dnd/jjakkak/domain/meeting/controller/MeetingControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/meeting/service/MeetingServiceTest.java
Labels: 🎨 feature

#49 Feature/#48 카테고리 테스트 코드 수정
  src/test/java/com/dnd/jjakkak/config/AbstractRestDocsTest.java
  src/test/java/com/dnd/jjakkak/domain/category/CategoryDummy.java
  src/test/java/com/dnd/jjakkak/domain/category/controller/CategoryControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/meeting/controller/MeetingControllerTest.java
Labels: 🎨 feature

#50 Feature/#45 authorize / controllerTest
  src/main/java/com/dnd/jjakkak/domain/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2SuccessHandler.java
  src/main/java/com/dnd/jjakkak/domain/meeting/controller/MeetingController.java
  src/main/java/com/dnd/jjakkak/domain/member/controller/AuthController.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityConfig.java
  src/test/java/com/dnd/jjakkak/config/AbstractRestDocsTest.java
  src/test/java/com/dnd/jjakkak/domain/member/controller/AuthControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/member/controller/MemberControllerTest.java
Labels: 🎨 feature

#53 Deploy/Security & 일정
  build.gradle
  src/docs/asciidoc/api/category.adoc
  src/docs/asciidoc/api/meeting.adoc
  src/main/java/com/dnd/jjakkak/domain/jwt/exception/AccessTokenExpiredException.java
  src/main/java/com/dnd/jjakkak/domain/jwt/exception/MalformedTokenException.java
  src/main/java/com/dnd/jjakkak/domain/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2FailureHandler.java
  src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2LogoutHandler.java
  src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2SuccessHandler.java
  src/main/java/com/dnd/jjakkak/domain/jwt/provider/JwtProvider.java
  src/main/java/com/dnd/jjakkak/domain/meeting/controller/MeetingController.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/request/MeetingCreateRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/request/MeetingUpdateRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingCreateResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/entity/Meeting.java
  src/main/java/com/dnd/jjakkak/domain/meeting/exception/MeetingUnauthorizedException.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/dnd/jjakkak/domain/meeting/service/MeetingService.java
  src/main/java/com/dnd/jjakkak/domain/meetingmember/entity/MeetingMember.java
  src/main/java/com/dnd/jjakkak/domain/meetingmember/repository/MeetingMemberRepository.java
  src/main/java/com/dnd/jjakkak/domain/meetingmember/repository/MeetingMemberRepositoryCustom.java
  src/main/java/com/dnd/jjakkak/domain/meetingmember/repository/MeetingMemberRepositoryImpl.java
  src/main/java/com/dnd/jjakkak/domain/member/controller/AuthController.java
  src/main/java/com/dnd/jjakkak/domain/member/controller/MemberController.java
  src/main/java/com/dnd/jjakkak/domain/member/dto/response/MemberResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/member/entity/Member.java
  src/main/java/com/dnd/jjakkak/domain/member/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/dnd/jjakkak/domain/member/service/MemberService.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityConfig.java
  src/main/resources/static/index.html
  src/test/java/com/dnd/jjakkak/config/AbstractRestDocsTest.java
  src/test/java/com/dnd/jjakkak/config/JjakkakMockSecurityContext.java
  src/test/java/com/dnd/jjakkak/config/JjakkakMockUser.java
  src/test/java/com/dnd/jjakkak/config/RestDocsConfiguration.java
  src/test/java/com/dnd/jjakkak/domain/category/CategoryDummy.java
  src/test/java/com/dnd/jjakkak/domain/category/controller/CategoryControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/meeting/MeetingDummy.java
  src/test/java/com/dnd/jjakkak/domain/meeting/controller/MeetingControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/meeting/service/MeetingServiceTest.java
  src/test/java/com/dnd/jjakkak/domain/meetingcategory/repository/MeetingCategoryRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/member/controller/AuthControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/member/controller/MemberControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/member/repository/BlacklistedTokenRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/member/service/BlacklistServiceTest.java
Labels: deploy

#54 Deploy/Filter 오류 수정 후 재배포
  src/main/java/com/dnd/jjakkak/domain/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/dnd/jjakkak/domain/member/controller/AuthController.java
  src/main/java/com/dnd/jjakkak/global/config/security/FailedAuthenticationEntryPoint.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityConfig.java
  src/main/resources/static/favicon.ico
  src/main/resources/static/index.html
Labels: deploy

#67 Feature/#63 로그인 처리 및 토큰 재발급
  build.gradle
  src/main/java/com/dnd/jjakkak/JjakkakApplication.java
  src/main/java/com/dnd/jjakkak/domain/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2SuccessHandler.java
  src/main/java/com/dnd/jjakkak/domain/member/controller/AuthController.java
  src/main/java/com/dnd/jjakkak/domain/member/controller/LoginController.java
  src/main/java/com/dnd/jjakkak/domain/member/service/AuthService.java
  src/main/java/com/dnd/jjakkak/domain/member/service/MemberService.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityConfig.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityEndpointPaths.java
  src/main/resources/templates/login.html
Labels: feature, refactor

#68 Deploy/로그인 구현 배포
  build.gradle
  src/main/java/com/dnd/jjakkak/JjakkakApplication.java
  src/main/java/com/dnd/jjakkak/domain/dateofschedule/dto/request/DateOfScheduleCreateRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/dateofschedule/entity/DateOfSchedule.java
  src/main/java/com/dnd/jjakkak/domain/dateofschedule/repository/DateOfScheduleRepository.java
  src/main/java/com/dnd/jjakkak/domain/dateofschedule/service/DateOfScheduleService.java
  src/main/java/com/dnd/jjakkak/domain/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2SuccessHandler.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/request/MeetingCreateRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/exception/MeetingFullException.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryCustom.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryImpl.java
  src/main/java/com/dnd/jjakkak/domain/meeting/service/MeetingService.java
  src/main/java/com/dnd/jjakkak/domain/member/controller/AuthController.java
  src/main/java/com/dnd/jjakkak/domain/member/controller/LoginController.java
  src/main/java/com/dnd/jjakkak/domain/member/entity/BlacklistedToken.java
  src/main/java/com/dnd/jjakkak/domain/member/service/AuthService.java
  src/main/java/com/dnd/jjakkak/domain/member/service/MemberService.java
  src/main/java/com/dnd/jjakkak/domain/schedule/controller/ScheduleController.java
  src/main/java/com/dnd/jjakkak/domain/schedule/dto/request/ScheduleAssignRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/schedule/dto/request/ScheduleUpdateRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/schedule/dto/response/ScheduleAssignResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/schedule/dto/response/ScheduleResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/schedule/entity/Schedule.java
  src/main/java/com/dnd/jjakkak/domain/schedule/exception/ScheduleAlreadyAssignedException.java
  src/main/java/com/dnd/jjakkak/domain/schedule/exception/ScheduleNotFoundException.java
  src/main/java/com/dnd/jjakkak/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/dnd/jjakkak/domain/schedule/repository/ScheduleRepositoryCustom.java
  src/main/java/com/dnd/jjakkak/domain/schedule/repository/ScheduleRepositoryImpl.java
  src/main/java/com/dnd/jjakkak/domain/schedule/service/ScheduleService.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityConfig.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityEndpointPaths.java
  src/main/resources/templates/login.html
  src/test/java/com/dnd/jjakkak/domain/meeting/service/MeetingServiceTest.java
  src/test/java/com/dnd/jjakkak/domain/member/controller/AuthControllerTest.java
Labels: deploy

#69 Deploy/로그 삭제 후 재배포
  src/main/java/com/dnd/jjakkak/domain/jwt/filter/JwtAuthenticationFilter.java
Labels: deploy

#70 Deploy/cors 설정
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityConfig.java
Labels: deploy

#71 Deploy/redirect URL 수정
  src/main/java/com/dnd/jjakkak/JjakkakApplication.java
  src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2FailureHandler.java
  src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2SuccessHandler.java
  src/main/java/com/dnd/jjakkak/domain/jwt/provider/JwtProvider.java
  src/main/java/com/dnd/jjakkak/global/config/proprties/JjakkakProperties.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityConfig.java
Labels: deploy

#72 Deploy/쿠키 samesite 설정
  src/main/java/com/dnd/jjakkak/domain/jwt/handler/OAuth2SuccessHandler.java
Labels: deploy

#75 Refactor/#52 모임 수정
  src/docs/asciidoc/api/meeting.adoc
  src/docs/asciidoc/api/member.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/jjakkak/domain/dateofschedule/dto/request/DateOfScheduleCreateRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/dateofschedule/entity/DateOfSchedule.java
  src/main/java/com/dnd/jjakkak/domain/dateofschedule/exception/ScheduleDateOutOfMeetingDateException.java
  src/main/java/com/dnd/jjakkak/domain/dateofschedule/repository/DateOfScheduleRepository.java
  src/main/java/com/dnd/jjakkak/domain/dateofschedule/service/DateOfScheduleService.java
  src/main/java/com/dnd/jjakkak/domain/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/dnd/jjakkak/domain/meeting/controller/MeetingController.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingCreateResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingInfoResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingMyPageResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingParticipantResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingTimeResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/entity/Meeting.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryCustom.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryImpl.java
  src/main/java/com/dnd/jjakkak/domain/meeting/service/MeetingService.java
  src/main/java/com/dnd/jjakkak/domain/meetingcategory/entity/MeetingCategory.java
  src/main/java/com/dnd/jjakkak/domain/meetingmember/repository/MeetingMemberRepositoryCustom.java
  src/main/java/com/dnd/jjakkak/domain/meetingmember/repository/MeetingMemberRepositoryImpl.java
  src/main/java/com/dnd/jjakkak/domain/member/controller/MemberController.java
  src/main/java/com/dnd/jjakkak/domain/member/exception/UnauthorizedException.java
  src/main/java/com/dnd/jjakkak/domain/member/service/MemberService.java
  src/main/java/com/dnd/jjakkak/domain/schedule/controller/ScheduleController.java
  src/main/java/com/dnd/jjakkak/domain/schedule/repository/ScheduleRepositoryImpl.java
  src/main/java/com/dnd/jjakkak/domain/schedule/service/ScheduleService.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityEndpointPaths.java
  src/main/resources/static/index.html
  src/test/java/com/dnd/jjakkak/config/JjakkakMockSecurityContext.java
  src/test/java/com/dnd/jjakkak/domain/meeting/MeetingDummy.java
  src/test/java/com/dnd/jjakkak/domain/meeting/controller/MeetingControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/meeting/service/MeetingServiceTest.java
  src/test/java/com/dnd/jjakkak/domain/member/controller/MemberControllerTest.java
Labels: feature

#78 Refactor/#77 모임 리팩토링
  src/main/java/com/dnd/jjakkak/domain/meeting/controller/MeetingController.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingParticipantResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/enums/MeetingSort.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryCustom.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryImpl.java
  src/main/java/com/dnd/jjakkak/domain/meeting/service/MeetingService.java
  src/main/java/com/dnd/jjakkak/domain/schedule/entity/Schedule.java
  src/main/java/com/dnd/jjakkak/domain/schedule/service/ScheduleService.java
  src/test/java/com/dnd/jjakkak/domain/meeting/MeetingDummy.java
  src/test/java/com/dnd/jjakkak/domain/meeting/controller/MeetingControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/meeting/service/MeetingServiceTest.java
Labels: refactor

#84 Fix/#81 모임 일정 마감시간 변경
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/request/MeetingConfirmRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/request/MeetingCreateRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingInfoResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/entity/Meeting.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryImpl.java
  src/main/java/com/dnd/jjakkak/domain/meeting/service/MeetingService.java
  src/main/java/com/dnd/jjakkak/domain/meetingmember/repository/MeetingMemberRepositoryImpl.java
  src/main/resources/static/index.html
  src/test/java/com/dnd/jjakkak/domain/meeting/MeetingDummy.java
  src/test/java/com/dnd/jjakkak/domain/meeting/controller/MeetingControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/meetingcategory/repository/MeetingCategoryRepositoryTest.java
Labels: feature
