Repository dnd-side-project/dnd-11th-7-backend, pull requests merged in 2024-07, with the labels that each got.

#2 Feature/#1 프로젝트 초기 세팅
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  build.gradle
  src/main/java/com/dnd/tikitaka/TikitakaApplication.java
  src/main/java/com/dnd/tikitaka/domain/example/controller/ExampleController.java
  src/main/java/com/dnd/tikitaka/domain/example/dto/request/ExampleCreateRequestDto.java
  src/main/java/com/dnd/tikitaka/domain/example/dto/response/ExampleResponse.java
  src/main/java/com/dnd/tikitaka/domain/example/entity/Example.java
  src/main/java/com/dnd/tikitaka/domain/example/exception/ExampleNotFoundException.java
  src/main/java/com/dnd/tikitaka/domain/example/repository/ExampleRepository.java
  src/main/java/com/dnd/tikitaka/domain/example/service/ExampleService.java
  src/main/java/com/dnd/tikitaka/global/config/security/SecurityConfig.java
  src/main/java/com/dnd/tikitaka/global/exception/GeneralException.java
  src/main/resources/application.properties
  src/test/java/com/dnd/tikitaka/TikitakaApplicationTests.java
Labels: ⚒️ setting

#7 Feature/#5 배포
  .github/workflows/deploy.yml
  Dockerfile
  src/main/java/com/dnd/zzaekkac/domain/example/controller/ExampleController.java
  src/main/java/com/dnd/zzaekkac/domain/example/controller/MainController.java
Labels: 🌍 deploy

#8 CI/CD
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/com/dnd/zzaekkac/ZzaekkacApplication.java
  src/main/java/com/dnd/zzaekkac/domain/example/controller/ExampleController.java
  src/main/java/com/dnd/zzaekkac/domain/example/controller/MainController.java
  src/main/java/com/dnd/zzaekkac/domain/example/dto/request/ExampleCreateRequestDto.java
  src/main/java/com/dnd/zzaekkac/domain/example/dto/request/ExampleUpdateRequestDto.java
  src/main/java/com/dnd/zzaekkac/domain/example/dto/response/ExampleResponse.java
  src/main/java/com/dnd/zzaekkac/domain/example/entity/Example.java
  src/main/java/com/dnd/zzaekkac/domain/example/exception/ExampleAlreadyExistsException.java
  src/main/java/com/dnd/zzaekkac/domain/example/exception/ExampleNotFoundException.java
  src/main/java/com/dnd/zzaekkac/domain/example/repository/ExampleRepository.java
  src/main/java/com/dnd/zzaekkac/domain/example/service/ExampleService.java
  src/main/java/com/dnd/zzaekkac/global/config/security/SecurityConfig.java
  src/main/java/com/dnd/zzaekkac/global/exception/ErrorResponse.java
  src/main/java/com/dnd/zzaekkac/global/exception/ExceptionController.java
  src/main/java/com/dnd/zzaekkac/global/exception/GeneralException.java
  src/main/resources/application.properties
  src/test/java/com/dnd/zzaekkac/ZzaekkacApplicationTests.java
Labels: 🌍 deploy

#9 deploy: CI/CD 테스트
  build.gradle
  src/main/java/com/dnd/zzaekkac/domain/example/controller/MainController.java
Labels: 🌍 deploy

#10 Feature/#6 카카오 로그인
  .gitignore
  build.gradle
  src/main/generated/com/dnd/zzaekkac/domain/example/entity/QExample.java
  src/main/generated/com/dnd/zzaekkac/domain/member/entity/QMember.java
  src/main/java/com/dnd/zzaekkac/domain/member/entity/Member.java
  src/main/java/com/dnd/zzaekkac/domain/member/entity/Role.java
  src/main/java/com/dnd/zzaekkac/domain/member/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/dnd/zzaekkac/domain/member/jwt/handler/OAuth2SuccessHandler.java
  src/main/java/com/dnd/zzaekkac/domain/member/jwt/provider/JwtProvider.java
  src/main/java/com/dnd/zzaekkac/domain/member/repository/MemberRepository.java
  src/main/java/com/dnd/zzaekkac/domain/member/service/MemberService.java
  src/main/java/com/dnd/zzaekkac/global/config/security/SecurityConfig.java
Labels: 🎨 feature

#21 Feature/#20 카테고리
  build.gradle
  src/docs/asciidoc/api/category.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/zzaekkac/domain/category/controller/CategoryController.java
  src/main/java/com/dnd/zzaekkac/domain/category/dto/response/CategoryResponseDto.java
  src/main/java/com/dnd/zzaekkac/domain/category/entity/Category.java
  src/main/java/com/dnd/zzaekkac/domain/category/exception/CategoryNotFoundException.java
  src/main/java/com/dnd/zzaekkac/domain/category/repository/CategoryRepository.java
  src/main/java/com/dnd/zzaekkac/domain/category/repository/CategoryRepositoryCustom.java
  src/main/java/com/dnd/zzaekkac/domain/category/repository/CategoryRepositoryImpl.java
  src/main/java/com/dnd/zzaekkac/domain/category/service/CategoryService.java
  src/test/java/com/dnd/zzaekkac/domain/category/controller/CategoryControllerTest.java
Labels: 🎨 feature

#24 DEPLOY / 서비스명 변경 후 재배포
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: 🌍 deploy

#25 DEPLOY / Spring REST Docs 페이지 추가
  .gitignore
  src/main/resources/static/index.html
Labels: 📝 docs, 🌍 deploy

#26 Feature/#20 카테고리 테스트 추가
  src/test/java/com/dnd/jjakkak/JjakkakApplicationTests.java
  src/test/java/com/dnd/jjakkak/domain/category/repository/CategoryRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/category/service/CategoryServiceTest.java
Labels: 🎨 feature

#22 Feature/#19 logout
  .gitignore
  src/main/java/com/dnd/jjakkak/JjakkakApplication.java
  src/main/java/com/dnd/jjakkak/domain/member/controller/AuthController.java
  src/main/java/com/dnd/jjakkak/domain/member/entity/BlacklistedToken.java
  src/main/java/com/dnd/jjakkak/domain/member/entity/Member.java
  src/main/java/com/dnd/jjakkak/domain/member/entity/RefreshToken.java
  src/main/java/com/dnd/jjakkak/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/dnd/jjakkak/domain/member/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/dnd/jjakkak/domain/member/jwt/handler/OAuth2SuccessHandler.java
  src/main/java/com/dnd/jjakkak/domain/member/jwt/provider/JwtProvider.java
  src/main/java/com/dnd/jjakkak/domain/member/repository/BlacklistedTokenRepository.java
  src/main/java/com/dnd/jjakkak/domain/member/repository/MemberRepository.java
  src/main/java/com/dnd/jjakkak/domain/member/repository/RefreshTokenRepository.java
  src/main/java/com/dnd/jjakkak/domain/member/service/BlacklistService.java
  src/main/java/com/dnd/jjakkak/domain/member/service/MemberService.java
  src/main/java/com/dnd/jjakkak/domain/member/service/RefreshTokenService.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityConfig.java
  src/test/java/com/dnd/jjakkak/domain/member/controller/AuthControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/member/jwt/filter/JJwtAuthenticationFilterTest.java
  src/test/java/com/dnd/jjakkak/domain/member/jwt/handler/OAuth2SuccessHandlerTest.java
  src/test/java/com/dnd/jjakkak/domain/member/jwt/provider/JwtProviderTest.java
  src/test/java/com/dnd/jjakkak/domain/member/repository/BlacklistedTokenRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/member/repository/MemberRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/member/repository/RefreshTokenRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/member/service/BlacklistServiceTest.java
  src/test/java/com/dnd/jjakkak/domain/member/service/MemberServiceTest.java
  src/test/java/com/dnd/jjakkak/domain/member/service/RefreshTokenServiceTest.java
Labels: 🎨 feature

#27 Feature/#18 모임 API 구현 및 테스트
  src/docs/asciidoc/api/category.adoc
  src/docs/asciidoc/api/meeting.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/jjakkak/domain/meeting/controller/MeetingController.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/request/MeetingConfirmRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/request/MeetingCreateRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/request/MeetingUpdateRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/entity/Meeting.java
  src/main/java/com/dnd/jjakkak/domain/meeting/exception/InvalidMeetingDateException.java
  src/main/java/com/dnd/jjakkak/domain/meeting/exception/MeetingNotFoundException.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/dnd/jjakkak/domain/meeting/service/MeetingService.java
  src/main/java/com/dnd/jjakkak/domain/meetingcategory/entity/MeetingCategory.java
  src/main/java/com/dnd/jjakkak/domain/meetingcategory/repository/MeetingCategoryRepository.java
  src/main/java/com/dnd/jjakkak/domain/meetingcategory/repository/MeetingCategoryRepositoryCustom.java
  src/main/java/com/dnd/jjakkak/domain/meetingcategory/repository/MeetingCategoryRepositoryImpl.java
  src/main/resources/static/index.html
  src/test/java/com/dnd/jjakkak/domain/category/controller/CategoryControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/meeting/MeetingDummy.java
  src/test/java/com/dnd/jjakkak/domain/meeting/controller/MeetingControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/meeting/service/MeetingServiceTest.java
  src/test/java/com/dnd/jjakkak/domain/meetingcategory/repository/MeetingCategoryRepositoryTest.java
  src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-fields.snippet
Labels: 🎨 feature

#31 Feature/#29 member
  src/main/java/com/dnd/jjakkak/domain/member/controller/MemberController.java
  src/main/java/com/dnd/jjakkak/domain/member/dto/request/MemberUpdateNicknameRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/member/dto/request/MemberUpdateProfileRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/member/entity/BlacklistedToken.java
  src/main/java/com/dnd/jjakkak/domain/member/entity/Member.java
  src/main/java/com/dnd/jjakkak/domain/member/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/dnd/jjakkak/domain/member/repository/MemberRepository.java
  src/main/java/com/dnd/jjakkak/domain/member/service/BlacklistService.java
  src/main/java/com/dnd/jjakkak/domain/member/service/MemberOAuth2Service.java
  src/main/java/com/dnd/jjakkak/domain/member/service/MemberService.java
  src/test/java/com/dnd/jjakkak/domain/member/service/MemberServiceTest.java
Labels: 🎨 feature

#35 DEPLOY / 중간 배포
  .gitignore
  README.md
  src/docs/asciidoc/api/category.adoc
  src/docs/asciidoc/api/meeting.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/jjakkak/JjakkakApplication.java
  src/main/java/com/dnd/jjakkak/domain/category/controller/CategoryController.java
  src/main/java/com/dnd/jjakkak/domain/meeting/controller/MeetingController.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/request/MeetingConfirmRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/request/MeetingCreateRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/request/MeetingUpdateRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/entity/Meeting.java
  src/main/java/com/dnd/jjakkak/domain/meeting/exception/InvalidMeetingDateException.java
  src/main/java/com/dnd/jjakkak/domain/meeting/exception/MeetingNotFoundException.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/dnd/jjakkak/domain/meeting/service/MeetingService.java
  src/main/java/com/dnd/jjakkak/domain/meetingcategory/entity/MeetingCategory.java
  src/main/java/com/dnd/jjakkak/domain/meetingcategory/repository/MeetingCategoryRepository.java
  src/main/java/com/dnd/jjakkak/domain/meetingcategory/repository/MeetingCategoryRepositoryCustom.java
  src/main/java/com/dnd/jjakkak/domain/meetingcategory/repository/MeetingCategoryRepositoryImpl.java
  src/main/java/com/dnd/jjakkak/domain/member/controller/AuthController.java
  src/main/java/com/dnd/jjakkak/domain/member/controller/MemberController.java
  src/main/java/com/dnd/jjakkak/domain/member/dto/request/MemberUpdateNicknameRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/member/dto/request/MemberUpdateProfileRequestDto.java
  src/main/java/com/dnd/jjakkak/domain/member/entity/BlacklistedToken.java
  src/main/java/com/dnd/jjakkak/domain/member/entity/Member.java
  src/main/java/com/dnd/jjakkak/domain/member/entity/RefreshToken.java
  src/main/java/com/dnd/jjakkak/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/dnd/jjakkak/domain/member/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/dnd/jjakkak/domain/member/jwt/handler/OAuth2SuccessHandler.java
  src/main/java/com/dnd/jjakkak/domain/member/jwt/provider/JwtProvider.java
  src/main/java/com/dnd/jjakkak/domain/member/repository/BlacklistedTokenRepository.java
  src/main/java/com/dnd/jjakkak/domain/member/repository/MemberRepository.java
  src/main/java/com/dnd/jjakkak/domain/member/repository/RefreshTokenRepository.java
  src/main/java/com/dnd/jjakkak/domain/member/service/BlacklistService.java
  src/main/java/com/dnd/jjakkak/domain/member/service/MemberOAuth2Service.java
  src/main/java/com/dnd/jjakkak/domain/member/service/MemberService.java
  src/main/java/com/dnd/jjakkak/domain/member/service/RefreshTokenService.java
  src/main/java/com/dnd/jjakkak/global/config/security/FailedAuthenticationEntryPoint.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityConfig.java
  src/main/resources/static/index.html
  src/test/java/com/dnd/jjakkak/JjakkakApplicationTests.java
  src/test/java/com/dnd/jjakkak/domain/category/controller/CategoryControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/category/repository/CategoryRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/category/service/CategoryServiceTest.java
  src/test/java/com/dnd/jjakkak/domain/meeting/MeetingDummy.java
  src/test/java/com/dnd/jjakkak/domain/meeting/controller/MeetingControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/meeting/service/MeetingServiceTest.java
  src/test/java/com/dnd/jjakkak/domain/meetingcategory/repository/MeetingCategoryRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/member/controller/AuthControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/member/repository/BlacklistedTokenRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/member/repository/MemberRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/member/repository/RefreshTokenRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/member/service/BlacklistServiceTest.java
  src/test/java/com/dnd/jjakkak/domain/member/service/RefreshTokenServiceTest.java
  src/test/resources/application-test.properties
  src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-fields.snippet
Labels: 🌍 deploy

#36 Feature/#33 meeting member
  src/main/java/com/dnd/jjakkak/domain/meeting/controller/MeetingController.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/service/MeetingService.java
  src/main/java/com/dnd/jjakkak/domain/meetingmember/entity/MeetingMember.java
  src/main/java/com/dnd/jjakkak/domain/meetingmember/repository/MeetingMemberRepository.java
  src/main/java/com/dnd/jjakkak/domain/meetingmember/repository/MeetingMemberRepositoryCustom.java
  src/main/java/com/dnd/jjakkak/domain/meetingmember/repository/MeetingMemberRepositoryImpl.java
  src/main/java/com/dnd/jjakkak/domain/member/controller/MemberController.java
  src/main/java/com/dnd/jjakkak/domain/member/dto/response/MemberResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/member/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/dnd/jjakkak/domain/member/jwt/provider/JwtProvider.java
  src/main/java/com/dnd/jjakkak/domain/member/service/MemberService.java
  src/test/java/com/dnd/jjakkak/domain/member/repository/BlacklistedTokenRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/member/service/BlacklistServiceTest.java
Labels: 🎨 feature
