Repository dnd-side-project/dnd-11th-7-backend, pull requests merged in 2024-10, with the labels that each got.

#126 [Refactor] 모임 일정 시간 페이징 처리 및 베스트 타임 API
  docker/docker-compose.yml
  src/main/java/com/dnd/jjakkak/domain/meeting/controller/MeetingController.java
  src/main/java/com/dnd/jjakkak/domain/meeting/dto/response/MeetingTimeResponseDto.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryCustom.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryImpl.java
  src/main/java/com/dnd/jjakkak/domain/meeting/service/MeetingService.java
  src/main/java/com/dnd/jjakkak/domain/schedule/entity/Schedule.java
  src/main/java/com/dnd/jjakkak/domain/schedule/service/ScheduleService.java
  src/main/java/com/dnd/jjakkak/global/common/PageInfo.java
  src/main/java/com/dnd/jjakkak/global/common/PagedResponse.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityEndpointPaths.java
  src/main/resources/static/index.html
  src/test/java/com/dnd/jjakkak/domain/meeting/MeetingDummy.java
  src/test/java/com/dnd/jjakkak/domain/meeting/controller/MeetingControllerTest.java
  src/test/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/meeting/service/MeetingServiceTest.java
Labels: refactor

#128 [Refactor] 모임의 일정 마감 시간 적용
  src/main/java/com/dnd/jjakkak/domain/meeting/exception/MeetingAlreadyEndedException.java
  src/main/java/com/dnd/jjakkak/domain/schedule/service/ScheduleService.java
  src/test/java/com/dnd/jjakkak/domain/schedule/ScheduleDummy.java
  src/test/java/com/dnd/jjakkak/domain/schedule/service/ScheduleServiceTest.java
Labels: refactor

#134 [Feat] JWT 필터 권한 체크 로직 수정
  src/main/java/com/dnd/jjakkak/domain/jwt/filter/JwtAuthenticationFilter.java
Labels: refactor

#137 [Fix] 일정 할당 동시성 제어
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryCustom.java
  src/main/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryImpl.java
  src/main/java/com/dnd/jjakkak/domain/redis/RedisRepository.java
  src/main/java/com/dnd/jjakkak/domain/refreshtoken/service/RefreshTokenService.java
  src/main/java/com/dnd/jjakkak/domain/schedule/controller/ScheduleController.java
  src/main/java/com/dnd/jjakkak/domain/schedule/facade/ScheduleFacade.java
  src/main/java/com/dnd/jjakkak/domain/schedule/service/ScheduleService.java
  src/test/java/com/dnd/jjakkak/domain/meeting/repository/MeetingRepositoryTest.java
  src/test/java/com/dnd/jjakkak/domain/schedule/controller/ScheduleControllerTest.java
Labels: bug

#139 refactor: 분산락 Redisson으로 적용 및 AOP로 적용
  build.gradle
  src/main/java/com/dnd/jjakkak/domain/schedule/controller/ScheduleController.java
  src/main/java/com/dnd/jjakkak/domain/schedule/facade/ScheduleFacade.java
  src/main/java/com/dnd/jjakkak/domain/schedule/service/ScheduleService.java
  src/main/java/com/dnd/jjakkak/global/annotation/redisson/RedissonLock.java
  src/main/java/com/dnd/jjakkak/global/annotation/redisson/RedissonLockAspect.java
  src/main/java/com/dnd/jjakkak/global/annotation/redisson/TransactionAspect.java
  src/main/java/com/dnd/jjakkak/global/config/redis/RedisConfig.java
  src/main/java/com/dnd/jjakkak/global/config/redis/RedissonConfig.java
  src/main/java/com/dnd/jjakkak/global/util/CustomSpringELParser.java
  src/test/java/com/dnd/jjakkak/domain/schedule/controller/ScheduleControllerTest.java
Labels: bug, refactor

#144 [Fix] 일정 - URI 수정
  src/main/java/com/dnd/jjakkak/domain/schedule/controller/ScheduleController.java
  src/main/java/com/dnd/jjakkak/global/config/security/SecurityEndpointPaths.java
Labels: bug

#145 [Fix] 일정 수정 오류
  src/main/java/com/dnd/jjakkak/domain/dateofschedule/service/DateOfScheduleService.java
  src/main/java/com/dnd/jjakkak/domain/schedule/service/ScheduleService.java
  src/test/java/com/dnd/jjakkak/domain/schedule/service/ScheduleServiceTest.java
Labels: bug
